### ISSUE TITLE
2021-11-08 メルブラ プレマ

### ISSUE THREAD

**Issue by pankona** [pankona/til#3]
## 感想など

アルクェイド使用。
@mtsmfm さん @testtatto さんと延々対戦。@highwide さんも参戦だけど機材の関係で対戦はできず。
40戦くらいしたような気がする。9割以上は負けた。グロい。

- 「詐欺重ね」というテクニックを知った。起き攻めは実は読み合いになってなかったことを知る。みんな生き汚い。素直に読み合いをしろ
  - 詐欺重ねをされると、こちらが被起き攻めであるとして、こちらがガードを選択したら相手の攻撃が発生してガードさせられ、こちらが昇竜だとか開放を選択するとガード (あるいはシールド) される、みたいな状況になる。
  - リバサ昇竜とか開放とかの発生が 10F 弱くらい (細かい値はわからぬ) らしく、起き上がってから発生するまでの時間を利用して両対応とするテクニックのようだ。
  - むずそうじゃん？って思うけどどうも状況によっては簡単に再現できるっぽい。
  - 対応としては、素直にガードするか、あるいはリバサバックダッシュで難を逃れることができる場合もあるっぽい。
    - 画面端で詐欺重ねされる場合、バックダッシュで技をスカしてもその後のスキに技をくらっちゃうことがあるっぽくて全然安定ではない気がする。むしろ期待値低いんでは…？
  - シールド貼るというのも対策のひとつかもしれない
    - シールド発動すればシールド後の読み合いへ。読み勝っても読み合いが続くあたりが理不尽であるな。
    - シールド読まれて相手が何もしないで着地した場合はやむなし。念仏を唱えろ
  - ということで、詐欺重ね対策は結局のところ「通常ガードかシールドか」みたいなところが取れる選択かな？
  - 重ねをミスることを期待して昇竜打ってもいいかもしれないが、ガードされたらもれなくお仕置きをもらうことを考えるとあんまり得策ではない気はする。開放も同様であんまり妥当な選択でないという印象
  - ムーンドライブからのムーンスキル、みたいなことをやってもなんとなく仕切り直せるかもしれない
- 236A溜めは強いんだけど連携がワンパなせいかシールドで取られたり割り込まれたりするケースがまあまああった。
  - 何度もループさせないほうがいいなって思った。一度の連携で出しても一回までにしとこ
- 昇竜ガードされ後のスキ消しムーンドライブが出ない？
  - ムーンドライブでスキを消せるはず？という理解だが一回もうまく行かなかった。良いマトだった
  - ちなみに昇竜ガードされたら 1/3 くらい体力もっていかれることを覚悟しないといけないが、弱昇竜なら割とごまかしが効くような気がしないでもない。リバサこするときは弱昇竜を出そう。

## 次回に向けてメモ

- 詐欺重ねに対しては通常ガードかシールドかを原則にする。
  - 画面端以外ならばバックダッシュもたまにね。画面端だと期待値低いと思う。たぶん。
  - ムーンドライブからのムーンスキルで相打ち狙った特攻も良いのかもしれない。無駄かも。まあ試してみる。
  - 昇竜や開放は詐欺重ねをバッチリやる人に対しては封印でも良いかもしれない。ちゃんと重なってないなら昇竜出せばいいけども、出すなら弱で。
- コンボがいい加減安いのでちょっとレパートリー増やしたほうがいいかもね
  - 特に相手を空中ではたき落としたとき。よくあるシチュエーションの割にあんまりダメージにつながっていない
  - C 溜めがヒットしたときなんかもコンボできるんじゃないのか。あと 236A 出し切りが当たったときなんかも何かコンボできそう。要調査。
- あとそろそろ違うキャラを触っていったほうがいいね。

**Comment by testtatto** [comment]
>画面端で詐欺重ねされる場合、バックダッシュで技をスカしてもその後のスキに技をくらっちゃうことがあるっぽくて全然安定ではない気がする。むしろ期待値低いんでは…？

画面中央だと距離取れるので期待値は高いが、画面端だと負ける択が多いです

>ムーンドライブからのムーンスキル、みたいなことをやってもなんとなく仕切り直せるかもしれない

択の1つとしてはアリ。ただ、密着で詐欺重ねをムーンドライブの無敵でスカした場合だと、ムーンスキルが投げに負けるので注意

詐欺重ねに関して、一番有効なのはファジー小パンor投げですかね。
すかし下段、すかし投げの択に勝てて、JC重ねはガードできる。ただ、むずい
やり方わからなければ聞いてください。

>ちなみに昇竜ガードされたら 1/3 くらい体力もっていかれることを覚悟しないといけないが、弱昇竜なら割とごまかしが効くような気がしないでもない。リバサこするときは弱昇竜を出そう。

アルクの22Aは無敵ねぇンだわ...

**Comment by pankona** [comment]
@testtatto

> 詐欺重ねに関して、一番有効なのはファジー小パンor投げですかね。
> すかし下段、すかし投げの択に勝てて、JC重ねはガードできる。ただ、むずい
> やり方わからなければ聞いてください。

なるほど。原理はわかると思うが… タイミングむずそうやな… 普通に JC 重ねを食らう未来が見える…
頑張ってみます、サンキュー！

> アルクの22Aは無敵ねぇンだわ...

はーつっかえ
